name: Playwright Java CI integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Playwright GitHub Action
        uses: microsoft/playwright-github-action@v1
        with:
          args: install

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Create directories for properties files
        run: mkdir -p src/main/resources

      - name: Create secrets.properties
        run: |
          echo "student.email=${{ secrets.STUDENT_EMAIL }}" > src/main/resources/secrets.properties
          echo "student.password=${{ secrets.STUDENT_PASSWORD }}" >> src/main/resources/secrets.properties
          echo "teacher.email=${{ secrets.TEACHER_EMAIL }}" >> src/main/resources/secrets.properties
          echo "teacher.password=${{ secrets.TEACHER_PASSWORD }}" >> src/main/resources/secrets.properties

      - name: Create configuration.properties
        run: |
          echo "nbc.url=${{ secrets.NBC_URL }}" > src/main/resources/configurations.properties

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install XVFB
        run: sudo apt-get install -y xvfb

      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress

      - name: Run Maven Integration Tests
        run: xvfb-run -a mvn test -Pintegration-tests

      - name: Generate HTML Report
        run: xvfb-run -a mvn surefire-report:report-only

      - name: Generate Site for HTML Report
        run: xvfb-run -a mvn site -DskipTests

      - name: Check if report exists
        run: ls -R ${{ github.workspace }}/target/site || echo "Report directory does not exist"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            ${{ github.workspace }}/target/site/surefire-report.html
